version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_paintbloatware
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_new:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - paintbloatware_network
      
  minio:
    image: quay.io/minio/minio
    container_name: paintbloatware_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - paintbloatware_network
      
  backend:
    image: ghcr.io/corcho4433/paintbloatware-backend:prisma-port
    container_name: backend_paintbloatware
    ports:
      - "60014:60014"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_URL: ${MINIO_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      FRONTEND_PATH: ${FRONTEND_PATH}
      MP_WEBHOOK_SECRET: ${MP_WEBHOOK_SECRET}
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      NITRO_PLAN_ID: ${NITRO_PLAN_ID}
      PORT: 60014
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - minio
    networks:
      - paintbloatware_network
      
  rust_backend:
    image: ghcr.io/niitroxendioxide/pbw-backend:main
    container_name: rust_backend_paintbloatware
    ports:
      - "8080:8080"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_PUBLIC_ENDPOINT: /minio
      RUST_LOG: info
    depends_on:
      - db
      - minio
    networks:
      - paintbloatware_network
      
  frontend:
    image: ghcr.io/corcho4433/paintbloatware:master
    container_name: frontend_paint
    ports:
      - "60015:60015"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      - backend
      - rust_backend
    networks:
      - paintbloatware_network
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    command: tunnel --config /etc/cloudflared/config.docker.yml run
    volumes:
      - C:/Users/${USER}/.cloudflared:/etc/cloudflared:ro
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    networks:
      - paintbloatware_network
      
volumes:
  postgres_data_new:
    driver: local
  minio_data:
    driver: local
    
networks:
  paintbloatware_network:
    driver: bridge